apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-project-3-kubernetes
  labels:
    app: hello
    'backstage.io/kubernetes-id': springboot-project-3
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
        'backstage.io/kubernetes-id': springboot-project-3
    spec:
      containers:
      - name: hello-app
        image: docker.io/nuga99/IMAGE:GITHUB_SHA
        ports:
        - containerPort: 8080